import json
from pathlib import Path

import pytest

from comp_research_mas.agents import build_debate_points, decide_debate_points, critique_step_report
from comp_research_mas.graph import run_step5
from comp_research_mas.guardian import guardian_node, scan_state, scan_text
from comp_research_mas.notifier import prepare_notifier_dry_run
from comp_research_mas.personas import all_personas
from comp_research_mas.query_planner import build_query_plan
from comp_research_mas.rag import retrieve_related_evidence
from comp_research_mas.research_adapter import HermesResearchAdapter
from comp_research_mas.vector_store import FileVectorStore


def test_guardian_block_warn_and_pass():
    assert scan_text("safe public text").severity == "pass"
    warn = scan_text("이 자료는 내부자료 검토용")
    assert warn.severity == "warn"
    block = scan_text("삼성 내부 원가 정보")
    assert block.severity == "block"


def test_guardian_scans_raw_results_and_draft():
    state = {"period_id": "2026-06", "raw_results": {"results": [{"raw_text": "confidential"}]}, "draft": "safe"}
    result = scan_state(state)
    assert result.severity == "warn"
    blocked = guardian_node({"period_id": "2026-06", "draft": "삼성 미공개 정보"})
    assert blocked["hard_fail"] is True
    assert blocked["guardian_result"]["severity"] == "block"


def test_hermes_research_adapter_injected_and_validation(tmp_path):
    plan = build_query_plan("2026-26", period_id="2026-06")
    raw = {
        "period_id": "2026-06",
        "week_id": "2026-26",
        "results": [
            {
                "query_id": "q1",
                "source_url": "https://example.com/a",
                "source_date": "2026-06-01",
                "source_type": "official",
                "title": "title",
                "summary": "summary",
                "raw_text": "raw",
                "competitor": "GMCC/Midea",
                "compressor_type": "Re",
                "category": "신제품·라인업",
                "refrigerants": ["R290"],
                "samsung_status": "미보유",
            }
        ],
    }
    path = tmp_path / "raw.json"
    path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    loaded = HermesResearchAdapter(path).search(plan)
    assert loaded["period_id"] == "2026-06"
    assert HermesResearchAdapter.trust_distribution(loaded)["high_confidence"] == 1

    bad_path = tmp_path / "bad.json"
    bad_path.write_text(json.dumps({"results": [{"query_id": "q"}]}), encoding="utf-8")
    with pytest.raises(ValueError):
        HermesResearchAdapter(bad_path).search(plan)


def test_hermes_research_adapter_fallback_to_stub():
    plan = build_query_plan("2026-26", period_id="2026-06")
    raw = HermesResearchAdapter().search(plan)
    assert raw["results"]
    assert raw["period_id"] == "2026-06"


def test_file_vector_store_and_rag_period_search():
    ledger = {
        "periods": {
            "2026-06": {
                "evidence": [
                    {"compressor_type": "Re", "competitor": "GMCC/Midea", "category": "신제품·라인업", "trust_score": 5, "dynamic_tags": ["Re", "신제품·라인업"], "evidence_id": "e1"},
                    {"compressor_type": "Ro", "competitor": "LG", "category": "성능·효율", "trust_score": 3, "dynamic_tags": ["Ro"], "evidence_id": "e2"},
                ]
            }
        }
    }
    found = FileVectorStore(ledger).search("Re", "GMCC/Midea", "신제품·라인업")
    assert found[0]["evidence_id"] == "e1"
    # RAG uses the real ledger generated by step5 sample; just assert callable/list contract.
    assert isinstance(retrieve_related_evidence(compressor_type="Re", competitor="GMCC/Midea", category="신제품·라인업"), list)


def test_debate_points_accepted_rejected_and_not_needed():
    assert build_debate_points(10, [], False) == []
    major = build_debate_points(6, ["출처 목록에 source name/url/date를 포함하세요."], False)
    assert major[0]["severity"] == "major"
    assert decide_debate_points(major)[0]["decision"] == "accepted"
    minor = build_debate_points(8, ["문체를 더 간결하게 조정하세요."], False)
    assert minor[0]["severity"] == "minor"
    assert decide_debate_points(minor)[0]["decision"] == "rejected"


def test_notifier_dry_run_outbox_and_payloads():
    state = {
        "period_id": "2026-06",
        "draft": "# report\n\n## 이번 주 핵심 동향 요약\n- 핵심\n",
        "report_meta": {"high_threat_count": 2, "signal_count": 1},
        "output_paths": {"report": "outputs/reports/2026-06_compressor_monthly.md"},
    }
    result = prepare_notifier_dry_run(state)
    outbox = Path(result["notifier_outbox"])
    assert (outbox / "email_payload.json").exists()
    email = json.loads((outbox / "email_payload.json").read_text(encoding="utf-8"))
    assert email["to"] == "jh104.kim@samsung.com"
    assert email["attachment"].endswith(".md")
    obsidian = json.loads((outbox / "obsidian_payload.json").read_text(encoding="utf-8"))
    assert obsidian["vault_path"]


def test_personas_all_agents_exist():
    personas = all_personas()
    for key in ["source_planner", "research_adapter", "evidence_normalizer", "analyst", "writer", "critic", "guardian"]:
        assert key in personas
        assert personas[key]["role"]


def test_step5_graph_e2e_and_monthly_outputs():
    state = run_step5("2026-06")
    assert state["status"] == "saved"
    paths = state["output_paths"]
    assert paths["report"].endswith("2026-06_compressor_monthly.md")
    assert paths["review"].endswith("2026-06_critic_review.json")
    assert paths["critic_cot"].endswith("2026-06_critic_cot.json")
    assert paths["evidence"].endswith("2026-06_evidence.json")
    assert Path(paths["guardian"]).exists()
    assert Path(paths["notifier_dry_run"]).exists()
    assert Path(paths["email_payload"]).exists()
    assert any("persona_role" in item for item in state["reasoning_log"])


def test_orchestrator_sensitive_regex_removed():
    content = Path("src/comp_research_mas/orchestrator.py").read_text(encoding="utf-8")
    assert "SENSITIVE_RE" not in content
